### PR TITLE
Update html-quiz.md

### PR DESCRIPTION
**Pull request by spitlisk**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
I think and quite sure that before it was more informative and visible, but with your link it become more compact. I am thinking about to keep both your link and previous solution (table). What do you think @spitlisk? and also please use special markdown format for posting the link like `[](url)`

**Comment by spitlisk** [comment]
> I think and quite sure that before it was more informative and visible, but with your link it become more compact. I am thinking about to keep both your link and previous solution (table). What do you think @spitlisk? and also please use special markdown format for posting the link like `[](url)`

I put the link of the image to someone for the document like question 12 I don't know how to do it, I can learn.

**Comment by Ebazhanov** [comment]
> > I think and quite sure that before it was more informative and visible, but with your link it become more compact. I am thinking about to keep both your link and previous solution (table). What do you think @spitlisk? and also please use special markdown format for posting the link like `[](url)`
> 
> I put the link of the image to someone for the document like question 12 I don't know how to do it, I can learn.

Thanks would be great and ping me later when should I take a look again! Have a good day!

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @spitlisk! Please let me know if you need any help with this PR, waiting for your updates.

**Pull request closed without merging**
